name: Desire To Live Now
favicon: null
layout_spectrum: 1
typography_spectrum: 0.25344
title: Health Coaching with Tracey Mixon
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#93c01f'
    - '#652283'
    - '#a07aad'
    - '#e0d1e5'
  brandStrength: 1
  lightness: 0.524856117554009
  saturation: 0.05232815258204937
  rhythmicContrast: 0.5170550120528787
purpose: []
